version: '2.1'
services:
  sahib:
    image: registry.lpbk-bethel.de/sahib:latest
    command: bundle exec puma
    volumes:
      - ./plugins:/app/plugins
    ports:
      - "80:9393"
    depends_on:
      - pdf
    env_file:
      - config/${DATENBANK:-beispiel}.env

  pdf:
    image: registry.lpbk-bethel.de/pdf:latest
