source "http://rubygems.org"
  gem 'envyable'
  gem 'sequel'
  gem 'mysql2'
  gem 'json'
  gem 'schild', :github => 'hmt/schild', :branch => 'master'
  gem 'sinatra'
  gem 'sass'
  gem 'slim'
  gem 'puma'
